name: Run build on release
on: 
  pull_request:
    types: [closed]
    branches:
      - release
jobs:
  Run-Build-on-PR:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v2
        with:
          ref: release
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo "🖥️ The workflow is now will now build on the runner."
      - name: Run install
        run: npm install
      - name: Run build
        run: npm run build
      - run: echo "🍏 Build has finished"
      - name: Git commit
        run: | 
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "[Build] Creating build files"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release
       